### PR TITLE
refactor: nextjs-example page.tsx code refactored for better readability

### PR DESCRIPTION
**Pull request by abrahamvphilip**
Refactored the Card Component Rendering in page.tsx

Issue: The Card component was instantiated multiple times to render multiple content.

Solution: Implemented a more favorable approach by creating a 'cards' array of objects and utilizing the map function to render each Card component. This not only reduces code redundancy but also improves the maintainability and readability.

---

I tried earlier but had some issues and fixed that, but now there's one issue that persists and am not sure if this will work. Am sorry, didn't mean to do it twice. I've mentioned the issue in #93

### CODE REVIEW

**Review by necolas — CHANGES_REQUESTED** [review]
I don't think the indirection is an improvement. Nothing wrong with the existing code. I'll leave this open for a bit in case you want to submit just the typo fixes though

**Comment by abrahamvphilip** [comment]
> I don't think the indirection is an improvement. Nothing wrong with the existing code. I'll leave this open for a bit in case you want to submit just the typo fixes though

Uhh okay, no probs. i fixed the typo on my new code. do you want me to revert it back to original or this works?

**Comment by necolas** [comment]
Yes revert the changes please

**Review by nmn — APPROVED** [review]
Thanks for the grammar fixes.

**Pull request merged**
