### PR TITLE
use code frames for errors for babel plugin

### PR DESCRIPTION
**Pull request by EvanBacon**
## What changed / motivation ?

Using code frame errors will show the dev generally where the problem is:

## Additional Context

- I'm not familiar with the repo. Wouldn't be offended if you close the PR and replicate with preferred style.

Screenshots, Tests, Anything Else

Screenshot 2024-10-14 at 7 31 59 PM

## Pre-flight checklist

- [x] I have read the contributing guidelines
      [Contribution Guidelines](https://github.com/facebook/stylex/blob/main/.github/CONTRIBUTING.md)
- [x] Performed a self-review of my code

### CODE REVIEW

**Comment by nmn** [comment]
Thank you so much @EvanBacon 

I was about to start working on this task myself, and your solution is honestly better than what I had in mind.

There is probably further improvements that can be made further down the line, but this should already be a huge improvement in the meantime.

**Review by nmn — CHANGES_REQUESTED** [review]
If you can fix the Flow errors and failing tests then this looks good.

If you're not sure how to deal with Flow, I'm happy to do this for you!

**Comment by EvanBacon** [comment]
@nmn I think you should drive this. I just took a guess at where the errors are but I'm still getting used to stylex so I'm not sure what the DX should feel like. Specifically we point to the general `path` object when things go wrong, which is already an improvement, but it's possible that we could assert on the precise dynamic variables that are triggering the errors.

Will continue to brush up on stylex and the repo though so I can be more helpful in the future.

**Comment by nmn** [comment]
@EvanBacon Thank you for putting this up and getting it so far! I'll drive it from here.

**Review by nmn — APPROVED** [review]

**Pull request merged**
