### PR TITLE
feat: vscode integration

### PR DESCRIPTION
**Pull request by Yash-Singh1**
## What changed / motivation ?

I spent the last week or so building up an LSP for StyleX that I can use for a VSCode extension. This PR adds a link to it to the documentation in an integrations section to the API portion of the docs.

Link to VSCode extension: https://marketplace.visualstudio.com/items?itemName=yash-singh.stylex

## Linked PR/Issues

Fixes # (issue)

## Additional Context

Screenshots, Tests, Anything Else

## Pre-flight checklist

- [x] I have read the contributing guidelines
      [Contribution Guidelines](./CONTRIBUTING.md)
- [x] Performed a self-review of my code

### CODE REVIEW

**Comment by nmn** [comment]
This is not the right place for this link.

I'm planning on adding an "ecosystem" sidebar item under "learn" which will include a set of tools that can be used alongside StyleX. This will include editor plugins, babel plugins, UI libraries etc. along with a basic introduction to each project.

Once your plugin is a bit more polished, I'll make sure to add it there.

Therefore, I'm leaving this PR open but not merging it for now.

**Comment by necolas** [comment]
Do we have / need a VSCode extension for internal use of StyleX?

**Comment by nmn** [comment]
We don't have a VSCode plugin for internal use. There is little need for one as Typescript or Flow should provide auto-complete.

But seeing colors, and getting better auto-complete for CSS values can be nice.

**Comment by Yash-Singh1** [comment]
@nmn Quick status update here, I updated the VSCode extension and got the following working:

- Auto-complete
- Multi-byte Characters
- Fixed various bugs and issues that arised by testing the extension on the following examples:
	- StyleX `apps/examples`: https://github.com/facebook/stylex/tree/main/apps/nextjs-example, https://github.com/facebook/stylex/tree/main/apps/rollup-example, https://github.com/facebook/stylex/tree/main/apps/webpack-example
	- [`qwik-stylex`](https://github.com/nmn/qwik-stylex)
	- [`docusaurus-stylex`](https://github.com/nmn/docusaurus-stylex)
	- [`nextjs-app-dir-stylex`](https://github.com/nmn/nextjs-app-dir-stylex)
	- Most code snippets present in the documentation

LMK if you are looking for anything else or find any issues in the extension.

I also updated the PR and moved the documentation page to the ecosystem section.

**Comment by nmn** [comment]
@Yash-Singh1  Thanks for the great work on the VS Code plugin. I've been using it myself a bit recently, and I've found the inline colour pickers to be useful even before you added all these additional features.

Again, the website changes will have to wait, because I want to find a good place for "related tools". I will probably make an extra page and document `@stylexjs/open-props` and the VS Code plugin to start.

Leaving the PR open till I get around to that.

**Comment by nmn** [comment]
I fixed the conflict and merged it.

**Pull request closed without merging**
