### PR TITLE
fix: cta section responsive issue

### PR DESCRIPTION
**Pull request by mehedihsajib**
## What changed / motivation ?
FIX: CTA section's responsive issue fixed

### Issue was:
When screen size is around 370-380px the CTA section touches the edge which is not looks good (Please check the attached screenshot)

### Changes I made:
- There was several options to fix it. I just reduced the padding-x of those button when screen size is less then 390px

### Before:
cta-before

### After: 
cta-after

### Notes for Reviewers:
Hope you are going great. 
Please check my changes and if you have suggestions or need any modification please let me know. 

Thank you for your time and consideration!

## Pre-flight checklist

- [x] I have read the contributing guidelines
      [Contribution Guidelines](../CONTRIBUTING.md)
- [x] Performed a self-review of my code

### CODE REVIEW

**Review by nmn — CHANGES_REQUESTED** [review]
The CTA button is also used for the button the `/playground` page. We should add padding around the buttons instead.

**Comment by mehedihsajib** [comment]
> The CTA button is also used for the button the `/playground` page. We should add padding around the buttons instead.

Hi,
Thanks for your feedback. 
The parent of those button is 'flex' without 'flex-wrap' that's why when screen gets narrower the button crossed the screen and margin/padding not get reflected. 

So instead of using padding I just change the media query 360px to 385px and now it seems okay. 
If you still any better suggestion please do let me know.

Thanks.

**Review by nmn — APPROVED** [review]

**Comment by nmn** [comment]
Please fix the prettier failure.

**Comment by mehedihsajib** [comment]
> Please fix the prettier failure.

Hi, the prettier failure is fixed now.

**Pull request merged**
