### PR TITLE
Fix priority of three physical border properties.

### PR DESCRIPTION
**Pull request by etlovett**
## What changed / motivation ?

I was inspecting this file and noticed that these three properties appeared to be stored in the wrong priority set. The other physical longhands (e.g. `border-bottom-color` and `border-left-width`) are stored in `longHandPhysical`.

## Linked PR/Issues

None

## Additional Context

None

## Pre-flight checklist

- [x] I have read the contributing guidelines
      [Contribution Guidelines](https://github.com/facebook/stylex/blob/main/.github/CONTRIBUTING.md)
- [x] Performed a self-review of my code

### CODE REVIEW

**Review by nmn — APPROVED** [review]
Please accept the CLA so I can merge!

**Comment by etlovett** [comment]
> Please accept the CLA so I can merge!

Yep, will do! I'm working to figure out what the right channels are at my employer for this approval.

**Comment by etlovett** [comment]
@nmn FYI I have now signed the CLA. Feel free to merge!

**Comment by nmn** [comment]
Merged in 33d5e0ab0958c67eba3d878ceb062ce26fb151de

**Pull request closed without merging**
