### PR TITLE
chore: Add type references to package.json

### PR DESCRIPTION
**Pull request by kevintyj**
## What changed / motivation ?
Adds "types" to all of the packages' package.json (if the build output includes a type declaration)

## Linked PR/Issues
#46 

## Additional Context
[TS Docs](https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html)

## Pre-flight Checklist
- [x] I have read the [contributing guidelines](https://github.com/facebook/stylex/blob/main/.github/CONTRIBUTING.md)
- [x] I have signed the contributing [agreement](https://code.facebook.com/cla)
- [ ] I have written unit tests where necessary (If it is a feature commit)
- [x] Performed a self-review of my code
- [x] Made sure PR title follows the conventional commit specification

### CODE REVIEW

**Comment by nmn** [comment]
We use a different pattern to publish types where the type definition files shadow the source files. These files are regular Typescript code instead of declaration files.

AFAIK, this has been working correctly without the `"types"` field in package.json

I want to verify that this PR won't cause a regression before we can merge. Also, if a Typescript expert can chime in, that would be helpful.

**Comment by joshuajaco** [comment]
As long as the declaration file has the same name and path, as it does in this case, it will work.

See [package.json "main" and "types"](https://www.typescriptlang.org/docs/handbook/modules/reference.html#packagejson-main-and-types)
> If "types" and "typings" are not present or cannot be resolved, TypeScript will read the "main" field and perform [extension substitution](https://www.typescriptlang.org/docs/handbook/modules/reference.html#file-extension-substitution) to find a declaration file.

**Comment by nmn** [comment]
Thanks for the link @joshuajaco 

> When publishing a typed package to npm, it’s recommended to include a "types" field even if [extension substitution](https://www.typescriptlang.org/docs/handbook/modules/reference.html#file-extension-substitution) or [package.json "exports"](https://www.typescriptlang.org/docs/handbook/modules/reference.html#packagejson-exports) make it unnecessary, because npm shows a TS icon on the package registry listing only if the package.json contains a "types" field.

This confirms that adding the `types` field to package.json is an improvement. Happy to merge once you rebase.

**Comment by nmn** [comment]
Thank you for your PR @kevintyj !

This change and more has been incorporated in a different PR that also adds ESM support, so I'm now closing this PR.

**Pull request closed without merging**
